### ISSUE TITLE
renpy2linux did not fully create a binary executable under /lib

### ISSUE THREAD

**Issue by miniwark** [Shizmob/renpy2linux#1]
renpy2linux almost work:
- correctly detect the renpy version
- correctly download the SDK
- correctly unzip and install the missing libs

The only missing steep is adding a binary executable in the Linux libs.

For example, after converting a windows only game and launching `The Game.sh` i have the following error:
```
./The Game.sh: 60: exec: /home/somedude/Games/The_Game/lib/linux-x86_64/The Game: not found
```
Workaround: I was able to recreate the missing file by downloading a game already ready for Linux, coping the corresponding executable and renaming it in the right place.

**Comment by shizmob** [comment]
Looks like this was changed in recent Ren'Py versions - I'll push a fix this evening, thanks for reporting!
